import { Command } from 'commander'
import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import ora from 'ora'

export interface ScaffoldOptions {
  name: string
  dir?: string
}

const PLUGIN_TEMPLATE = (name: string, safeName: string) => `/**
 * ${name} — OpenComp plugin
 *
 * Generated by: opencomp scaffold plugin ${name}
 */
import { registerPlugin } from '@opencomp/sdk'

export const ${safeName}Plugin = {
  manifest: {
    name: '${name}',
    version: '0.1.0',
    compatibleWith: '^0.1.0',
    description: 'TODO: describe your plugin',
    author: 'TODO: your name',
  },
  extensions: {
    formulas: [],
  },
  onRegister() {
    console.log('[${name}] Plugin registered')
  },
}

// Register immediately when imported
registerPlugin(${safeName}Plugin)
`

const PLUGIN_PACKAGE_JSON = (name: string) =>
  JSON.stringify(
    {
      name,
      version: '0.1.0',
      description: 'OpenComp plugin',
      main: './dist/index.js',
      types: './dist/index.d.ts',
      scripts: {
        build: 'tsup src/index.ts --format cjs --dts',
        dev: 'tsup src/index.ts --format cjs --dts --watch',
        test: 'vitest run',
      },
      dependencies: {
        '@opencomp/sdk': '^0.1.0',
        '@opencomp/contracts': '^0.1.0',
      },
      devDependencies: {
        tsup: '^8.0.0',
        typescript: '^5.4.0',
        vitest: '^1.4.0',
      },
    },
    null,
    2,
  )

const TSCONFIG = JSON.stringify(
  {
    extends: '../../tsconfig.base.json',
    compilerOptions: { outDir: './dist', rootDir: './src' },
    include: ['src'],
  },
  null,
  2,
)

export function scaffoldCommand(): Command {
  const cmd = new Command('scaffold')
  cmd.description('Scaffold a new OpenComp plugin or module')

  cmd
    .command('plugin <name>')
    .description('Scaffold a new plugin in ./plugins/<name>')
    .option('-d, --dir <dir>', 'Target directory (default: ./plugins)')
    .action((name: string, options: { dir?: string }) => {
      const spinner = ora(`Scaffolding plugin: ${name}`).start()

      const baseDir = options.dir ?? './plugins'
      const pluginDir = join(baseDir, name, 'src')

      if (existsSync(join(baseDir, name))) {
        spinner.fail(`Plugin directory already exists: ${join(baseDir, name)}`)
        process.exit(1)
      }

      try {
        mkdirSync(pluginDir, { recursive: true })

        const safeName = name.replace(/[^a-zA-Z0-9]/g, '_').replace(/^[0-9]/, '_$&')

        writeFileSync(join(pluginDir, 'index.ts'), PLUGIN_TEMPLATE(name, safeName))
        writeFileSync(join(baseDir, name, 'package.json'), PLUGIN_PACKAGE_JSON(name))
        writeFileSync(join(baseDir, name, 'tsconfig.json'), TSCONFIG)

        spinner.succeed(`Plugin scaffolded at ${join(baseDir, name)}`)
        console.log('\nNext steps:')
        console.log(`  1. Edit ${join(baseDir, name, 'src', 'index.ts')}`)
        console.log(`  2. pnpm install`)
        console.log(`  3. Import and register in your API: import '${name}'`)
      } catch (err) {
        spinner.fail(`Failed to scaffold plugin: ${(err as Error).message}`)
        process.exit(1)
      }
    })

  return cmd
}
