/**
 * Sample Goal Sheet Template Plugin
 *
 * Demonstrates how to provide a custom goal sheet template via the OpenComp
 * plugin system. A real implementation would render a PDF or HTML document
 * by merging participant data with a branded layout.
 *
 * Install: npm install @opencomp/sdk @opencomp/contracts
 * Register: import and call registerPlugin() at API startup.
 */
import { registerPlugin } from '../../../packages/sdk/src'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface GoalSheetContext {
  participantId: string
  participantName: string
  periodName: string
  planName: string
  quotaAmountCents: number
  currency: string
  components: GoalSheetComponent[]
}

export interface GoalSheetComponent {
  name: string
  quotaAmountCents: number
  targetPayoutCents: number
  formulaDescription: string
}

export interface RenderedGoalSheet {
  /** MIME type of the rendered output */
  mimeType: 'text/html' | 'application/pdf' | 'text/plain'
  content: string
}

// ─── Renderer ─────────────────────────────────────────────────────────────────

function formatCents(cents: number, currency = 'USD'): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(cents / 100)
}

/**
 * Render a goal sheet as a self-contained HTML document.
 * Replace this with a PDF renderer (e.g. puppeteer) for production use.
 */
export function renderGoalSheetHtml(ctx: GoalSheetContext): RenderedGoalSheet {
  const componentRows = ctx.components
    .map(
      (c) => `
      <tr>
        <td>${c.name}</td>
        <td>${formatCents(c.quotaAmountCents, ctx.currency)}</td>
        <td>${formatCents(c.targetPayoutCents, ctx.currency)}</td>
        <td>${c.formulaDescription}</td>
      </tr>`,
    )
    .join('')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Goal Sheet — ${ctx.participantName}</title>
  <style>
    body { font-family: system-ui, sans-serif; color: #111; max-width: 800px; margin: 40px auto; padding: 0 24px; }
    h1 { font-size: 1.5rem; margin-bottom: 4px; }
    .meta { color: #666; font-size: 0.875rem; margin-bottom: 32px; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; }
    th { background: #f4f4f5; text-align: left; padding: 10px 12px; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; }
    td { padding: 10px 12px; border-bottom: 1px solid #e4e4e7; font-size: 0.9rem; }
    .total { font-weight: 600; }
    .footer { margin-top: 48px; font-size: 0.8rem; color: #888; border-top: 1px solid #e4e4e7; padding-top: 16px; }
  </style>
</head>
<body>
  <h1>Compensation Goal Sheet</h1>
  <div class="meta">
    <strong>${ctx.participantName}</strong> &nbsp;|&nbsp;
    ${ctx.periodName} &nbsp;|&nbsp;
    Plan: ${ctx.planName}
  </div>

  <h2>Quota &amp; Target Payout</h2>
  <table>
    <thead>
      <tr>
        <th>Component</th>
        <th>Quota</th>
        <th>Target Payout</th>
        <th>Formula</th>
      </tr>
    </thead>
    <tbody>
      ${componentRows}
      <tr class="total">
        <td>Total</td>
        <td>${formatCents(ctx.quotaAmountCents, ctx.currency)}</td>
        <td>${formatCents(ctx.components.reduce((s, c) => s + c.targetPayoutCents, 0), ctx.currency)}</td>
        <td></td>
      </tr>
    </tbody>
  </table>

  <div class="footer">
    Generated by OpenComp &nbsp;&bull;&nbsp; ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`

  return { mimeType: 'text/html', content: html }
}

// ─── Plugin registration ──────────────────────────────────────────────────────

export const sampleGoalSheetTemplatePlugin = {
  manifest: {
    name: '@opencomp/sample-goalsheet-template',
    version: '0.1.0',
    compatibleWith: '^0.1.0',
    description: 'Sample HTML goal sheet template renderer',
    author: 'OpenComp Contributors',
  },
  extensions: {},
  onRegister() {
    console.log('[sample-goalsheet-template] Plugin registered')
  },
}

// Register immediately when imported
registerPlugin(sampleGoalSheetTemplatePlugin)
